
            <span class="emoji-button" id="emoji-button">&#x263A;&#xFE0F;</span>
            <div class="emoji-toggle-box" id="emoji-toggle-box">
                <div class="tabs">
                    <div class="tab active" data-category="smileys">😊</div>
					<div class="tab" data-category="people">🤦🏻‍♂️</div>
                    <div class="tab" data-category="animals">🐼</div>
                    <div class="tab" data-category="food">🍕</div>
					<div class="tab" data-category="sports">⚽</div>
					<div class="tab" data-category="vehicles-places">🚗</div>
					<div class="tab" data-category="tools-accessories">💡</div>
					<div class="tab" data-category="signs">❤️</div>
					<div class="tab" data-category="plants">🌲</div>
					<div class="tab" data-category="weather">⛅</div>
                </div>
                <div class="emoji-toggle-content">
                    <!-- Emojis will be dynamically added here -->

<!--------------------------  smileys start------------------------------------------------------->
                    <span class="emoji" data-category="smileys">😀</span>
                    <span class="emoji" data-category="smileys">😃</span>
                    <span class="emoji" data-category="smileys">😄</span>
                    <span class="emoji" data-category="smileys">😁</span>
                    <span class="emoji" data-category="smileys">😆</span>
                    <span class="emoji" data-category="smileys">😅</span>
                    <span class="emoji" data-category="smileys">😂</span>
                    <span class="emoji" data-category="smileys">🤣</span>
                    <span class="emoji" data-category="smileys">🥲</span>
                    <span class="emoji" data-category="smileys">😊</span>
                    <span class="emoji" data-category="smileys">😇</span>
                    <span class="emoji" data-category="smileys">🙂</span>
                    <span class="emoji" data-category="smileys">🙃</span>
                    <span class="emoji" data-category="smileys">😉</span>
                    <span class="emoji" data-category="smileys">😌</span>
                    <span class="emoji" data-category="smileys">😍</span>
                    <span class="emoji" data-category="smileys">🥰</span>
                    <span class="emoji" data-category="smileys">😘</span>
                    <span class="emoji" data-category="smileys">😗</span>
                    <span class="emoji" data-category="smileys">😙</span>
                    <span class="emoji" data-category="smileys">😚</span>
                    <span class="emoji" data-category="smileys">😋</span>
                    <span class="emoji" data-category="smileys">😛</span>
                    <span class="emoji" data-category="smileys">😝</span>
                    <span class="emoji" data-category="smileys">😜</span>
                    <span class="emoji" data-category="smileys">🤪</span>
                    <span class="emoji" data-category="smileys">🤨</span>
                    <span class="emoji" data-category="smileys">🧐</span>
                    <span class="emoji" data-category="smileys">🤓</span>
                    <span class="emoji" data-category="smileys">😎</span>
                    <span class="emoji" data-category="smileys">🥸</span>
                    <span class="emoji" data-category="smileys">🤩</span>
                    <span class="emoji" data-category="smileys">🥳</span>
                    <span class="emoji" data-category="smileys">😏</span>
                    <span class="emoji" data-category="smileys">😒</span>
                    <span class="emoji" data-category="smileys">😞</span>
                    <span class="emoji" data-category="smileys">😔</span>
                    <span class="emoji" data-category="smileys">😟</span>
                    <span class="emoji" data-category="smileys">😕</span>
                    <span class="emoji" data-category="smileys">🙁</span>
                    <span class="emoji" data-category="smileys">☹️</span>
                    <span class="emoji" data-category="smileys">😣</span>
                    <span class="emoji" data-category="smileys">😖</span>
                    <span class="emoji" data-category="smileys">😫</span>
                    <span class="emoji" data-category="smileys">😩</span>
                    <span class="emoji" data-category="smileys">🥺</span>
                    <span class="emoji" data-category="smileys">😢</span>
                    <span class="emoji" data-category="smileys">😭</span>
                    <span class="emoji" data-category="smileys">😤</span>
                    <span class="emoji" data-category="smileys">😠</span>
                    <span class="emoji" data-category="smileys">😡</span>
                    <span class="emoji" data-category="smileys">🤬</span>
                    <span class="emoji" data-category="smileys">🤯</span>
                    <span class="emoji" data-category="smileys">😳</span>
                    <span class="emoji" data-category="smileys">🥵</span>
                    <span class="emoji" data-category="smileys">🥶</span>
                    <span class="emoji" data-category="smileys">😶‍🌫</span>
                    <span class="emoji" data-category="smileys">😱</span>
                    <span class="emoji" data-category="smileys">😨</span>
                    <span class="emoji" data-category="smileys">😰</span>
                    <span class="emoji" data-category="smileys">😥</span>
                    <span class="emoji" data-category="smileys">😓</span>
                    <span class="emoji" data-category="smileys">🤗</span>
                    <span class="emoji" data-category="smileys">🤔</span>
                    <span class="emoji" data-category="smileys">🤭</span>
                    <span class="emoji" data-category="smileys">🤫</span>
                    <span class="emoji" data-category="smileys">🤥</span>
                    <span class="emoji" data-category="smileys">😶</span>
                    <span class="emoji" data-category="smileys">😐</span>
                    <span class="emoji" data-category="smileys">😑</span>
                    <span class="emoji" data-category="smileys">😬</span>
                    <span class="emoji" data-category="smileys">🙄</span>
                    <span class="emoji" data-category="smileys">😯</span>
                    <span class="emoji" data-category="smileys">😦</span>
                    <span class="emoji" data-category="smileys">😧</span>
                    <span class="emoji" data-category="smileys">😮</span>
                    <span class="emoji" data-category="smileys">😲</span>
                    <span class="emoji" data-category="smileys">🥱</span>
                    <span class="emoji" data-category="smileys">😴</span>
                    <span class="emoji" data-category="smileys">🤤</span>
                    <span class="emoji" data-category="smileys">😪</span>
                    <span class="emoji" data-category="smileys">😮‍💨</span>
                    <span class="emoji" data-category="smileys">😵</span>
                    <span class="emoji" data-category="smileys">😵‍💫</span>
                    <span class="emoji" data-category="smileys">🤐</span>
                    <span class="emoji" data-category="smileys">🥴</span>
                    <span class="emoji" data-category="smileys">🤢</span>
                    <span class="emoji" data-category="smileys">🤮</span>
                    <span class="emoji" data-category="smileys">🤧</span>
                    <span class="emoji" data-category="smileys">😷</span>
                    <span class="emoji" data-category="smileys">🤒</span>
                    <span class="emoji" data-category="smileys">🤕</span>
                    <span class="emoji" data-category="smileys">🤑</span>
                    <span class="emoji" data-category="smileys">🤠</span>
                    <span class="emoji" data-category="smileys">😈</span>
                    <span class="emoji" data-category="smileys">👿</span>
                    <span class="emoji" data-category="smileys">👹</span>
                    <span class="emoji" data-category="smileys">👺</span>
                    <span class="emoji" data-category="smileys">🤡</span>
                    <span class="emoji" data-category="smileys">💩</span>
                    <span class="emoji" data-category="smileys">👻</span>
                    <span class="emoji" data-category="smileys">💀</span>
                    <span class="emoji" data-category="smileys">☠️</span>
                    <span class="emoji" data-category="smileys">👽</span>
                    <span class="emoji" data-category="smileys">👾</span>
                    <span class="emoji" data-category="smileys">🤖</span>
                    <span class="emoji" data-category="smileys">🎃</span>
                    <span class="emoji" data-category="smileys">😺</span>
                    <span class="emoji" data-category="smileys">😸</span>
                    <span class="emoji" data-category="smileys">😹</span>
                    <span class="emoji" data-category="smileys">😻</span>
                    <span class="emoji" data-category="smileys">😼</span>
                    <span class="emoji" data-category="smileys">😽</span>
                    <span class="emoji" data-category="smileys">🙀</span>
                    <span class="emoji" data-category="smileys">😿</span>
                    <span class="emoji" data-category="smileys">😾</span>
                    <span class="emoji" data-category="smileys">🤲🏻</span>
                    <span class="emoji" data-category="smileys">👐🏻</span>
                    <span class="emoji" data-category="smileys">🙌🏻</span>
                    <span class="emoji" data-category="smileys">👏🏻</span>
                    <span class="emoji" data-category="smileys">🤝</span>
                    <span class="emoji" data-category="smileys">👍🏻</span>
                    <span class="emoji" data-category="smileys">👎🏻</span>
                    <span class="emoji" data-category="smileys">👊🏻</span>
                    <span class="emoji" data-category="smileys">✊🏻</span>
                    <span class="emoji" data-category="smileys">🤛🏻</span>
                    <span class="emoji" data-category="smileys">🤜🏻</span>
                    <span class="emoji" data-category="smileys">🤞🏻</span>
                    <span class="emoji" data-category="smileys">✌🏻</span>
                    <span class="emoji" data-category="smileys">🤟🏻</span>
                    <span class="emoji" data-category="smileys">🤘🏻</span>
                    <span class="emoji" data-category="smileys">👌🏻</span>
                    <span class="emoji" data-category="smileys">🤌🏻</span>
                    <span class="emoji" data-category="smileys">🤏🏻</span>
                    <span class="emoji" data-category="smileys">👈🏻</span>
                    <span class="emoji" data-category="smileys">👉🏻</span>
                    <span class="emoji" data-category="smileys">👆🏻</span>
                    <span class="emoji" data-category="smileys">👇🏻</span>
                    <span class="emoji" data-category="smileys">☝🏻</span>
                    <span class="emoji" data-category="smileys">💪🏻</span>
                    <span class="emoji" data-category="smileys">🤚🏻</span>
                    <span class="emoji" data-category="smileys">🖐🏻</span>
                    <span class="emoji" data-category="smileys">✋🏻</span>
                    <span class="emoji" data-category="smileys">🖖🏻</span>
                    <span class="emoji" data-category="smileys">👋🏻</span>
                    <span class="emoji" data-category="smileys">🤙🏻</span>
                    <span class="emoji" data-category="smileys">💪🏻</span>
                    <span class="emoji" data-category="smileys">🦾</span>
                    <span class="emoji" data-category="smileys">🖕🏻</span>
                    <span class="emoji" data-category="smileys">✍🏻</span>
                    <span class="emoji" data-category="smileys">🙏🏻</span>
                    <span class="emoji" data-category="smileys">🦶🏻</span>
                    <span class="emoji" data-category="smileys">🦵🏻</span>
                    <span class="emoji" data-category="smileys">🦿</span>
                    <span class="emoji" data-category="smileys">💄</span>
                    <span class="emoji" data-category="smileys">💋</span>
                    <span class="emoji" data-category="smileys">👄</span>
                    <span class="emoji" data-category="smileys">🦷</span>
                    <span class="emoji" data-category="smileys">👅</span>
                    <span class="emoji" data-category="smileys">👃</span>
                    <span class="emoji" data-category="smileys">👂</span>
                    <span class="emoji" data-category="smileys">🦻</span>
                    <span class="emoji" data-category="smileys">👣</span>
                    <span class="emoji" data-category="smileys">👁️</span>
                    <span class="emoji" data-category="smileys">👀</span>
                    <span class="emoji" data-category="smileys">🫀</span>
                    <span class="emoji" data-category="smileys">🫁</span>
                    <span class="emoji" data-category="smileys">🧠</span>
                    <span class="emoji" data-category="smileys">🗣️</span>
                    <span class="emoji" data-category="smileys">👤</span>
                    <span class="emoji" data-category="smileys">👥</span>
                    <span class="emoji" data-category="smileys">🫂</span>


<!-----------------------smileys end ------------------------------------------------------>

<!----------------------people starts ------------------------------------------------------------>
					<span class="emoji" data-category="people">👶🏻</span>
				<span class="emoji" data-category="people">👧🏻</span>
				<span class="emoji" data-category="people">🧒🏻</span>
				<span class="emoji" data-category="people">👦🏻</span>
				<span class="emoji" data-category="people">👩🏻</span>
				<span class="emoji" data-category="people">🧑🏻</span>
				<span class="emoji" data-category="people">👨🏻</span>
				<span class="emoji" data-category="people">👩🏻‍🦱</span>
				<span class="emoji" data-category="people">🧑🏻‍🦱</span>
				<span class="emoji" data-category="people">👨🏻‍🦱</span>
				<span class="emoji" data-category="people">👩🏻‍🦰</span>
				<span class="emoji" data-category="people">🧑🏻‍🦰</span>
				<span class="emoji" data-category="people">👨🏻‍🦰</span>
				<span class="emoji" data-category="people">👱🏻‍♀️</span>
				<span class="emoji" data-category="people">👱🏻‍♂️</span>
				<span class="emoji" data-category="people">👩🏻‍🦳</span>
				<span class="emoji" data-category="people">🧑🏻‍🦳</span>
				<span class="emoji" data-category="people">👨🏻‍🦳</span>
				<span class="emoji" data-category="people">👩🏻‍🦲</span>
				<span class="emoji" data-category="people">🧑🏻‍🦲</span>
				<span class="emoji" data-category="people">👨🏻‍🦲</span>
				<span class="emoji" data-category="people">🧔🏻‍♀️</span>
				<span class="emoji" data-category="people">🧔🏻</span>
				<span class="emoji" data-category="people">🧔🏻‍♂️</span>
				<span class="emoji" data-category="people">👵🏻</span>
				<span class="emoji" data-category="people">🧓🏻</span>
				<span class="emoji" data-category="people">👴🏻</span>
				<span class="emoji" data-category="people">👲🏻</span>
				<span class="emoji" data-category="people">👳🏻‍♀️</span>
				<span class="emoji" data-category="people">👳🏻‍♂️</span>
				<span class="emoji" data-category="people">🧕🏻</span>
				<span class="emoji" data-category="people">👮🏻‍♀️</span>
				<span class="emoji" data-category="people">👮🏻‍♂️</span>
				<span class="emoji" data-category="people">👷🏻‍♀️</span>
				<span class="emoji" data-category="people">👷🏻‍♂️</span>
				<span class="emoji" data-category="people">💂🏻‍♀️</span>
				<span class="emoji" data-category="people">💂🏻‍♂️</span>
				<span class="emoji" data-category="people">🕵🏻‍♀️</span>
				<span class="emoji" data-category="people">🕵🏻‍♂️</span>
				<span class="emoji" data-category="people">👩🏻‍⚕️</span>
				<span class="emoji" data-category="people">🧑🏻‍⚕️</span>
				<span class="emoji" data-category="people">👨🏻‍⚕️</span>
				<span class="emoji" data-category="people">👩🏻‍🌾</span>
				<span class="emoji" data-category="people">🧑🏻‍🌾</span>
				<span class="emoji" data-category="people">👨🏻‍🌾</span>
				<span class="emoji" data-category="people">👩🏻‍🍳</span>
				<span class="emoji" data-category="people">🧑🏻‍🍳</span>
				<span class="emoji" data-category="people">👨🏻‍🍳</span>
				<span class="emoji" data-category="people">👩🏻‍🎓</span>
				<span class="emoji" data-category="people">🧑🏻‍🎓</span>
				<span class="emoji" data-category="people">👨🏻‍🎓</span>
				<span class="emoji" data-category="people">👩🏻‍🎤</span>
				<span class="emoji" data-category="people">🧑🏻‍🎤</span>
				<span class="emoji" data-category="people">👨🏻‍🎤</span>
				<span class="emoji" data-category="people">👩🏻‍🏫</span>
				<span class="emoji" data-category="people">🧑🏻‍🏫</span>
				<span class="emoji" data-category="people">👨🏻‍🏫</span>
				<span class="emoji" data-category="people">👩🏻‍🏭</span>
				<span class="emoji" data-category="people">🧑🏻‍🏭</span>
				<span class="emoji" data-category="people">👨🏻‍🏭</span>
				<span class="emoji" data-category="people">👩🏻‍💻</span>
				<span class="emoji" data-category="people">🧑🏻‍💻</span>
				<span class="emoji" data-category="people">👨🏻‍💻</span>
				<span class="emoji" data-category="people">👩🏻‍💼</span>
				<span class="emoji" data-category="people">🧑🏻‍💼</span>
				<span class="emoji" data-category="people">👨🏻‍💼</span>
				<span class="emoji" data-category="people">👩🏻‍🔧</span>
				<span class="emoji" data-category="people">🧑🏻‍🔧</span>
				<span class="emoji" data-category="people">👨🏻‍🔧</span>
				<span class="emoji" data-category="people">👩🏻‍🔬</span>
				<span class="emoji" data-category="people">🧑🏻‍🔬</span>
				<span class="emoji" data-category="people">👨🏻‍🔬</span>
				<span class="emoji" data-category="people">👩🏻‍🎨</span>
				<span class="emoji" data-category="people">🧑🏻‍🎨</span>
				<span class="emoji" data-category="people">👨🏻‍🎨</span>
				<span class="emoji" data-category="people">👩🏻‍🚒</span>
				<span class="emoji" data-category="people">🧑🏻‍🚒</span>
				<span class="emoji" data-category="people">👨🏻‍🚒</span>
				<span class="emoji" data-category="people">👩🏻‍✈️</span>
				<span class="emoji" data-category="people">🧑🏻‍✈️</span>
				<span class="emoji" data-category="people">👨🏻‍✈️</span>
				<span class="emoji" data-category="people">👩🏻‍🚀</span>
				<span class="emoji" data-category="people">🧑🏻‍🚀</span>
				<span class="emoji" data-category="people">👨🏻‍🚀</span>
				<span class="emoji" data-category="people">👩🏻‍⚖️</span>
				<span class="emoji" data-category="people">🧑🏻‍⚖️</span>
				<span class="emoji" data-category="people">👨🏻‍⚖️</span>
				<span class="emoji" data-category="people">👰🏻‍♀️</span>
				<span class="emoji" data-category="people">👰🏻</span>
				<span class="emoji" data-category="people">👰🏻‍♂️</span>
				<span class="emoji" data-category="people">🤵🏻‍♀️</span>
				<span class="emoji" data-category="people">🤵🏻</span>
				<span class="emoji" data-category="people">🤵🏻‍♂️</span>
				<span class="emoji" data-category="people">👸🏻</span>
				<span class="emoji" data-category="people">🤴🏻</span>
				<span class="emoji" data-category="people">🥷🏻</span>
				<span class="emoji" data-category="people">🦸🏻‍♀️</span>
				<span class="emoji" data-category="people">🦸🏻‍♂️</span>
				<span class="emoji" data-category="people">🦹🏻‍♀️</span>
				<span class="emoji" data-category="people">🦹🏻‍♂️</span>
				<span class="emoji" data-category="people">🤶🏻</span>
				<span class="emoji" data-category="people">🧑🏻‍🎄</span>
				<span class="emoji" data-category="people">🎅🏻</span>
				<span class="emoji" data-category="people">🧙🏻‍♀️</span>
				<span class="emoji" data-category="people">🧙🏻‍♂️</span>
				<span class="emoji" data-category="people">🧝🏻‍♀️</span>
				<span class="emoji" data-category="people">🧝🏻‍♂️</span>
				<span class="emoji" data-category="people">🧛🏻‍♀️</span>
				<span class="emoji" data-category="people">🧛🏻‍♂️</span>
				<span class="emoji" data-category="people">🧟‍♀️</span>
				<span class="emoji" data-category="people">🧟‍♂️</span>
				<span class="emoji" data-category="people">🧞‍♀️</span>
				<span class="emoji" data-category="people">🧞‍♂️</span>
				<span class="emoji" data-category="people">🧜🏻‍♀️</span>
				<span class="emoji" data-category="people">🧜🏻‍♂️</span>
				<span class="emoji" data-category="people">🧚🏻‍♀️</span>
				<span class="emoji" data-category="people">🧚🏻‍♂️</span>
				<span class="emoji" data-category="people">👼🏻</span>
				<span class="emoji" data-category="people">🤰🏻</span>
				<span class="emoji" data-category="people">🤱🏻</span>
				<span class="emoji" data-category="people">👩🏻‍🍼</span>
				<span class="emoji" data-category="people">🧑🏻‍🍼</span>
				<span class="emoji" data-category="people">👨🏻‍🍼</span>
				<span class="emoji" data-category="people">🙇🏻‍♀️</span>
				<span class="emoji" data-category="people">🙇🏻‍♂️</span>
				<span class="emoji" data-category="people">💁🏻‍♀️</span>
				<span class="emoji" data-category="people">💁🏻‍♂️</span>
				<span class="emoji" data-category="people">🙅🏻‍♀️</span>
				<span class="emoji" data-category="people">🙅🏻‍♂️</span>
				<span class="emoji" data-category="people">🙆🏻‍♀️</span>
				<span class="emoji" data-category="people">🙆🏻‍♂️</span>
				<span class="emoji" data-category="people">🙋🏻‍♀️</span>
				<span class="emoji" data-category="people">🙋🏻‍♂️</span>
				<span class="emoji" data-category="people">🧏🏻‍♀️</span>
				<span class="emoji" data-category="people">🧏🏻</span>
				<span class="emoji" data-category="people">🧏🏻‍♂️</span>
				<span class="emoji" data-category="people">🤦🏻‍♀️</span>
				<span class="emoji" data-category="people">🤦🏻‍♂️</span>
				<span class="emoji" data-category="people">🤷🏻‍♀️</span>
				<span class="emoji" data-category="people">🤷🏻‍♂️</span>
				<span class="emoji" data-category="people">🙎🏻‍♀️</span>
				<span class="emoji" data-category="people">🙎🏻‍♂️</span>
				<span class="emoji" data-category="people">🙍🏻‍♀️</span>
				<span class="emoji" data-category="people">🙍🏻‍♂️</span>
				<span class="emoji" data-category="people">💇🏻‍♀️</span>
				<span class="emoji" data-category="people">💇🏻‍♂️</span>
				<span class="emoji" data-category="people">💆🏻‍♀️</span>
				<span class="emoji" data-category="people">💆🏻‍♂️</span>
				<span class="emoji" data-category="people">🧖🏻‍♀️</span>
				<span class="emoji" data-category="people">🧖🏻‍♂️</span>
				<span class="emoji" data-category="people">💅🏻</span>
				<span class="emoji" data-category="people">🤳🏻</span>
				<span class="emoji" data-category="people">💃🏻</span>
				<span class="emoji" data-category="people">🕺🏻</span>
				<span class="emoji" data-category="people">👯🏻‍♀️</span>
				<span class="emoji" data-category="people">👯🏻‍♂️</span>
				<span class="emoji" data-category="people">🕴🏻</span>
				<span class="emoji" data-category="people">👩🏻‍🦽</span>
				<span class="emoji" data-category="people">🧑🏻‍🦽</span>
				<span class="emoji" data-category="people">👨🏻‍🦽</span>
				<span class="emoji" data-category="people">👩🏻‍🦼</span>
				<span class="emoji" data-category="people">🧑🏻‍🦼</span>
				<span class="emoji" data-category="people">👨🏻‍🦼</span>
				<span class="emoji" data-category="people">🚶🏻‍♀️</span>
				<span class="emoji" data-category="people">🚶🏻‍♂️</span>
				<span class="emoji" data-category="people">👩🏻‍🦯</span>
				<span class="emoji" data-category="people">🧑🏻‍🦯</span>
				<span class="emoji" data-category="people">👨🏻‍🦯</span>
				<span class="emoji" data-category="people">🧎🏻‍♀️</span>
				<span class="emoji" data-category="people">🧎🏻</span>
				<span class="emoji" data-category="people">🧎🏻‍♂️</span>
				<span class="emoji" data-category="people">🏃🏻‍♀️</span>
				<span class="emoji" data-category="people">🏃🏻‍♂️</span>
				<span class="emoji" data-category="people">🧍🏻‍♀️</span>
				<span class="emoji" data-category="people">🧍🏻</span>
				<span class="emoji" data-category="people">🧍🏻‍♂️</span>
				<span class="emoji" data-category="people">👫</span>
				<span class="emoji" data-category="people">👭</span>
				<span class="emoji" data-category="people">👬</span>
				<span class="emoji" data-category="people">👩‍❤️‍👨</span>
				<span class="emoji" data-category="people">👩‍❤️‍👩</span>
				<span class="emoji" data-category="people">💑</span>
				<span class="emoji" data-category="people">👨‍❤️‍👨</span>
				<span class="emoji" data-category="people">👩‍❤️‍💋‍👨</span>
				<span class="emoji" data-category="people">👩‍❤️‍💋‍👩</span>
				<span class="emoji" data-category="people">💏</span>
				<span class="emoji" data-category="people">👨‍❤️‍💋‍👨</span>
				<span class="emoji" data-category="people">👨‍👩‍👦</span>
				<span class="emoji" data-category="people">👨‍👩‍👧</span>
				<span class="emoji" data-category="people">👨‍👩‍👧‍👦</span>
				<span class="emoji" data-category="people">👨‍👩‍👦‍👦</span>
				<span class="emoji" data-category="people">👨‍👩‍👧‍👧</span>
				<span class="emoji" data-category="people">👩‍👩‍👦</span>
				<span class="emoji" data-category="people">👩‍👩‍👧</span>
				<span class="emoji" data-category="people">👩‍👩‍👧‍👦</span>
				<span class="emoji" data-category="people">👩‍👩‍👦‍👦</span>
				<span class="emoji" data-category="people">👩‍👩‍👧‍👧</span>
				<span class="emoji" data-category="people">👨‍👨‍👦</span>
				<span class="emoji" data-category="people">👨‍👨‍👧</span>
				<span class="emoji" data-category="people">👨‍👨‍👧‍👦</span>
				<span class="emoji" data-category="people">👨‍👨‍👦‍👦</span>
				<span class="emoji" data-category="people">👨‍👨‍👧‍👧</span>
				<span class="emoji" data-category="people">🪢</span>
				<span class="emoji" data-category="people">🧶</span>
				<span class="emoji" data-category="people">🧵</span>
				<span class="emoji" data-category="people">🪡</span>
				<span class="emoji" data-category="people">🧥</span>
				<span class="emoji" data-category="people">🥼</span>
				<span class="emoji" data-category="people">🦺</span>
				<span class="emoji" data-category="people">👚</span>
				<span class="emoji" data-category="people">👕</span>
				<span class="emoji" data-category="people">👖</span>
				<span class="emoji" data-category="people">🩲</span>
				<span class="emoji" data-category="people">🩳</span>
				<span class="emoji" data-category="people">👔</span>
				<span class="emoji" data-category="people">👗</span>
				<span class="emoji" data-category="people">👙</span>
				<span class="emoji" data-category="people">🩱</span>
				<span class="emoji" data-category="people">👘</span>
				<span class="emoji" data-category="people">🥻</span>
				<span class="emoji" data-category="people">🩴</span>
				<span class="emoji" data-category="people">🥿</span>
				<span class="emoji" data-category="people">👠</span>
				<span class="emoji" data-category="people">👡</span>
				<span class="emoji" data-category="people">👢</span>
				<span class="emoji" data-category="people">👞</span>
				<span class="emoji" data-category="people">👟</span>
				<span class="emoji" data-category="people">🥾</span>
				<span class="emoji" data-category="people">🧦</span>
				<span class="emoji" data-category="people">🧤</span>
				<span class="emoji" data-category="people">🧣</span>
				<span class="emoji" data-category="people">🎩</span>
				<span class="emoji" data-category="people">🧢</span>
				<span class="emoji" data-category="people">👒</span>
				<span class="emoji" data-category="people">🎓</span>
				<span class="emoji" data-category="people">⛑️</span>
				<span class="emoji" data-category="people">🪖</span>
				<span class="emoji" data-category="people">👑</span>
				<span class="emoji" data-category="people">💍</span>
				<span class="emoji" data-category="people">👝</span>
				<span class="emoji" data-category="people">👛</span>
				<span class="emoji" data-category="people">👜</span>
				<span class="emoji" data-category="people">💼</span>
				<span class="emoji" data-category="people">🎒</span>
				<span class="emoji" data-category="people">🧳</span>
				<span class="emoji" data-category="people">👓</span>
				<span class="emoji" data-category="people">🕶️</span>
				<span class="emoji" data-category="people">🥽</span>
				<span class="emoji" data-category="people">🌂</span>





<!--------------------------  people end--------------------------------------------------------->



<!----------------------------Animals start ------------------------------------------------------>
                    <span class="emoji" data-category="animals">🐶</span>
					<span class="emoji" data-category="animals">🐱</span>
					<span class="emoji" data-category="animals">🐭</span>
					<span class="emoji" data-category="animals">🐹</span>
					<span class="emoji" data-category="animals">🐰</span>
					<span class="emoji" data-category="animals">🦊</span>
					<span class="emoji" data-category="animals">🐻</span>
					<span class="emoji" data-category="animals">🐼</span>
					<span class="emoji" data-category="animals">🐻‍❄</span>
					<span class="emoji" data-category="animals">🐨</span>
					<span class="emoji" data-category="animals">🐯</span>
					<span class="emoji" data-category="animals">🦁</span>
					<span class="emoji" data-category="animals">🐮</span>
					<span class="emoji" data-category="animals">🐷</span>
					<span class="emoji" data-category="animals">🐽</span>
					<span class="emoji" data-category="animals">🐸</span>
					<span class="emoji" data-category="animals">🐵</span>
					<span class="emoji" data-category="animals">🙈</span>
					<span class="emoji" data-category="animals">🙉</span>
					<span class="emoji" data-category="animals">🙊</span>
					<span class="emoji" data-category="animals">🐒</span>
					<span class="emoji" data-category="animals">🐔</span>
					<span class="emoji" data-category="animals">🐧</span>
					<span class="emoji" data-category="animals">🐦</span>
					<span class="emoji" data-category="animals">🐤</span>
					<span class="emoji" data-category="animals">🐣</span>
					<span class="emoji" data-category="animals">🐥</span>
					<span class="emoji" data-category="animals">🦆</span>
					<span class="emoji" data-category="animals">🐦‍</span>
					<span class="emoji" data-category="animals">🦅</span>
					<span class="emoji" data-category="animals">🦉</span>
					<span class="emoji" data-category="animals">🦇</span>
					<span class="emoji" data-category="animals">🐺</span>
					<span class="emoji" data-category="animals">🐗</span>
					<span class="emoji" data-category="animals">🐴</span>
					<span class="emoji" data-category="animals">🦄</span>
					<span class="emoji" data-category="animals">🐝</span>
					<span class="emoji" data-category="animals">🪱</span>
					<span class="emoji" data-category="animals">🐛</span>
					<span class="emoji" data-category="animals">🦋</span>
					<span class="emoji" data-category="animals">🐌</span>
					<span class="emoji" data-category="animals">🐞</span>
					<span class="emoji" data-category="animals">🐜</span>
					<span class="emoji" data-category="animals">🪰</span>
					<span class="emoji" data-category="animals">🪲</span>
					<span class="emoji" data-category="animals">🪳</span>
					<span class="emoji" data-category="animals">🦟</span>
					<span class="emoji" data-category="animals">🦗</span>
					<span class="emoji" data-category="animals">🕷️</span>
					<span class="emoji" data-category="animals">🕸️</span>
					<span class="emoji" data-category="animals">🦂</span>
					<span class="emoji" data-category="animals">🐢</span>
					<span class="emoji" data-category="animals">🐍</span>
					<span class="emoji" data-category="animals">🦎</span>
					<span class="emoji" data-category="animals">🦖</span>
					<span class="emoji" data-category="animals">🦕</span>
					<span class="emoji" data-category="animals">🐙</span>
					<span class="emoji" data-category="animals">🦑</span>
					<span class="emoji" data-category="animals">🦐</span>
					<span class="emoji" data-category="animals">🦞</span>
					<span class="emoji" data-category="animals">🦀</span>
					<span class="emoji" data-category="animals">🐡</span>
					<span class="emoji" data-category="animals">🐠</span>
					<span class="emoji" data-category="animals">🐟</span>
					<span class="emoji" data-category="animals">🐬</span>
					<span class="emoji" data-category="animals">🐳</span>
					<span class="emoji" data-category="animals">🐋</span>
					<span class="emoji" data-category="animals">🦈</span>
					<span class="emoji" data-category="animals">🦭</span>
					<span class="emoji" data-category="animals">🐊</span>
					<span class="emoji" data-category="animals">🐅</span>
					<span class="emoji" data-category="animals">🐆</span>
					<span class="emoji" data-category="animals">🦓</span>
					<span class="emoji" data-category="animals">🦍</span>
					<span class="emoji" data-category="animals">🦧</span>
					<span class="emoji" data-category="animals">🦣</span>
					<span class="emoji" data-category="animals">🐘</span>
					<span class="emoji" data-category="animals">🦛</span>
					<span class="emoji" data-category="animals">🦏</span>
					<span class="emoji" data-category="animals">🐪</span>
					<span class="emoji" data-category="animals">🐫</span>
					<span class="emoji" data-category="animals">🦒</span>
					<span class="emoji" data-category="animals">🦘</span>
					<span class="emoji" data-category="animals">🦬</span>
					<span class="emoji" data-category="animals">🐃</span>
					<span class="emoji" data-category="animals">🐂</span>
					<span class="emoji" data-category="animals">🐄</span>
					<span class="emoji" data-category="animals">🐎</span>
					<span class="emoji" data-category="animals">🐖</span>
					<span class="emoji" data-category="animals">🐏</span>
					<span class="emoji" data-category="animals">🐑</span>
					<span class="emoji" data-category="animals">🦙</span>
					<span class="emoji" data-category="animals">🐐</span>
					<span class="emoji" data-category="animals">🦌</span>
					<span class="emoji" data-category="animals">🐕</span>
					<span class="emoji" data-category="animals">🐩</span>
					<span class="emoji" data-category="animals">🦮</span>
					<span class="emoji" data-category="animals">🐕‍🦺</span>
					<span class="emoji" data-category="animals">🐈</span>
					<span class="emoji" data-category="animals">🐈‍⬛</span>
					<span class="emoji" data-category="animals">🪶</span>
					<span class="emoji" data-category="animals">🐓</span>
					<span class="emoji" data-category="animals">🦃</span>
					<span class="emoji" data-category="animals">🦤</span>
					<span class="emoji" data-category="animals">🦚</span>
					<span class="emoji" data-category="animals">🦜</span>
					<span class="emoji" data-category="animals">🦢</span>
					<span class="emoji" data-category="animals">🦩</span>
					<span class="emoji" data-category="animals">🕊️</span>
					<span class="emoji" data-category="animals">🐇</span>
					<span class="emoji" data-category="animals">🦝</span>
					<span class="emoji" data-category="animals">🦨</span>
					<span class="emoji" data-category="animals">🦡</span>
					<span class="emoji" data-category="animals">🦫</span>
					<span class="emoji" data-category="animals">🦦</span>
					<span class="emoji" data-category="animals">🐁</span>
					<span class="emoji" data-category="animals">🐀</span>
					<span class="emoji" data-category="animals">🐿️</span>
					<span class="emoji" data-category="animals">🦔</span>
					<span class="emoji" data-category="animals">🐾</span>
					<span class="emoji" data-category="animals">🐉</span>
					<span class="emoji" data-category="animals">🐲</span>
					<span class="emoji" data-category="animals">🐚</span>
					<span class="emoji" data-category="animals">🪨</span>
<!-----------------------------------Animals End------------------------------------------------------------>



<!-----------------------------------Foods Start------------------------------------------------------------->

					<span class="emoji" data-category="food">🍔</span>
                    <span class="emoji" data-category="food">🍕</span>
                    <span class="emoji" data-category="food">🍦</span>
					<span class="emoji" data-category="food">🍔</span>
                    <span class="emoji" data-category="food">🍕</span>
                    <span class="emoji" data-category="food">🍦</span>
					<span class="emoji" data-category="food">🍔</span>
                    <span class="emoji" data-category="food">🍕</span>
                    <span class="emoji" data-category="food">🍦</span>
					<span class="emoji" data-category="food">🍔</span>
                    <span class="emoji" data-category="food">🍕</span>
                    <span class="emoji" data-category="food">🍦</span>
					<span class="emoji" data-category="food">🍔</span>
                    <span class="emoji" data-category="food">🍕</span>
                    <span class="emoji" data-category="food">🍦</span>
					<span class="emoji" data-category="food">🍔</span>
                    <span class="emoji" data-category="food">🍕</span>
                    <span class="emoji" data-category="food">🍦</span>
					<span class="emoji" data-category="food">🍏</span>
					<span class="emoji" data-category="food">🍎</span>
					<span class="emoji" data-category="food">🍐</span>
					<span class="emoji" data-category="food">🍊</span>
					<span class="emoji" data-category="food">🍋</span>
					<span class="emoji" data-category="food">🍌</span>
					<span class="emoji" data-category="food">🍉</span>
					<span class="emoji" data-category="food">🍇</span>
					<span class="emoji" data-category="food">🍓</span>
					<span class="emoji" data-category="food">🫐</span>
					<span class="emoji" data-category="food">🍈</span>
					<span class="emoji" data-category="food">🍒</span>
					<span class="emoji" data-category="food">🍑</span>
					<span class="emoji" data-category="food">🥭</span>
					<span class="emoji" data-category="food">🍍</span>
					<span class="emoji" data-category="food">🥥</span>
					<span class="emoji" data-category="food">🥝</span>
					<span class="emoji" data-category="food">🍅</span>
					<span class="emoji" data-category="food">🍆</span>
					<span class="emoji" data-category="food">🥑</span>
					<span class="emoji" data-category="food">🥦</span>
					<span class="emoji" data-category="food">🥬</span>
					<span class="emoji" data-category="food">🥒</span>
					<span class="emoji" data-category="food">🌶️</span>
					<span class="emoji" data-category="food">🫑</span>
					<span class="emoji" data-category="food">🌽</span>
					<span class="emoji" data-category="food">🥕</span>
					<span class="emoji" data-category="food">🫒</span>
					<span class="emoji" data-category="food">🧄</span>
					<span class="emoji" data-category="food">🧅</span>
					<span class="emoji" data-category="food">🥔</span>
					<span class="emoji" data-category="food">🍠</span>
					<span class="emoji" data-category="food">🥐</span>
					<span class="emoji" data-category="food">🥯</span>
					<span class="emoji" data-category="food">🍞</span>
					<span class="emoji" data-category="food">🥖</span>
					<span class="emoji" data-category="food">🥨</span>
					<span class="emoji" data-category="food">🧀</span>
					<span class="emoji" data-category="food">🥚</span>
					<span class="emoji" data-category="food">🍳</span>
					<span class="emoji" data-category="food">🧈</span>
					<span class="emoji" data-category="food">🥞</span>
					<span class="emoji" data-category="food">🧇</span>
					<span class="emoji" data-category="food">🥓</span>
					<span class="emoji" data-category="food">🥩</span>
					<span class="emoji" data-category="food">🍗</span>
					<span class="emoji" data-category="food">🍖</span>
					<span class="emoji" data-category="food">🦴</span>
					<span class="emoji" data-category="food">🌭</span>
					<span class="emoji" data-category="food">🍔</span>
					<span class="emoji" data-category="food">🍟</span>
					<span class="emoji" data-category="food">🍕</span>
					<span class="emoji" data-category="food">🫓</span>
					<span class="emoji" data-category="food">🥪</span>
					<span class="emoji" data-category="food">🥙</span>
					<span class="emoji" data-category="food">🧆</span>
					<span class="emoji" data-category="food">🌮</span>
					<span class="emoji" data-category="food">🌯</span>
					<span class="emoji" data-category="food">🫔</span>
					<span class="emoji" data-category="food">🥗</span>
					<span class="emoji" data-category="food">🥘</span>
					<span class="emoji" data-category="food">🫕</span>
					<span class="emoji" data-category="food">🥫</span>
					<span class="emoji" data-category="food">🫙</span>
					<span class="emoji" data-category="food">🍝</span>
					<span class="emoji" data-category="food">🍜</span>
					<span class="emoji" data-category="food">🍲</span>
					<span class="emoji" data-category="food">🍛</span>
					<span class="emoji" data-category="food">🍣</span>
					<span class="emoji" data-category="food">🍱</span>
					<span class="emoji" data-category="food">🥟</span>
					<span class="emoji" data-category="food">🦪</span>
					<span class="emoji" data-category="food">🍤</span>
					<span class="emoji" data-category="food">🍙</span>
					<span class="emoji" data-category="food">🍚</span>
					<span class="emoji" data-category="food">🍘</span>
					<span class="emoji" data-category="food">🍥</span>
					<span class="emoji" data-category="food">🥠</span>
					<span class="emoji" data-category="food">🥮</span>
					<span class="emoji" data-category="food">🍢</span>
					<span class="emoji" data-category="food">🍡</span>
					<span class="emoji" data-category="food">🍧</span>
					<span class="emoji" data-category="food">🍨</span>
					<span class="emoji" data-category="food">🍦</span>
					<span class="emoji" data-category="food">🥧</span>
					<span class="emoji" data-category="food">🧁</span>
					<span class="emoji" data-category="food">🍰</span>
					<span class="emoji" data-category="food">🎂</span>
					<span class="emoji" data-category="food">🍮</span>
					<span class="emoji" data-category="food">🍭</span>
					<span class="emoji" data-category="food">🍬</span>
					<span class="emoji" data-category="food">🍫</span>
					<span class="emoji" data-category="food">🍿</span>
					<span class="emoji" data-category="food">🍩</span>
					<span class="emoji" data-category="food">🍪</span>
					<span class="emoji" data-category="food">🌰</span>
					<span class="emoji" data-category="food">🥜</span>
					<span class="emoji" data-category="food">🍯</span>
					<span class="emoji" data-category="food">🥛</span>
					<span class="emoji" data-category="food">🍼</span>
					<span class="emoji" data-category="food">🫖</span>
					<span class="emoji" data-category="food">☕</span>
					<span class="emoji" data-category="food">🍵</span>
					<span class="emoji" data-category="food">🧃</span>
					<span class="emoji" data-category="food">🥤</span>
					<span class="emoji" data-category="food">🧋</span>
					<span class="emoji" data-category="food">🍶</span>
					<span class="emoji" data-category="food">🍺</span>
					<span class="emoji" data-category="food">🍻</span>
					<span class="emoji" data-category="food">🥂</span>
					<span class="emoji" data-category="food">🍷</span>
					<span class="emoji" data-category="food">🥃</span>
					<span class="emoji" data-category="food">🍸</span>
					<span class="emoji" data-category="food">🍹</span>
					<span class="emoji" data-category="food">🧉</span>
					<span class="emoji" data-category="food">🍾</span>
					<span class="emoji" data-category="food">🧊</span>
					<span class="emoji" data-category="food">🥄</span>
					<span class="emoji" data-category="food">🍴</span>
					<span class="emoji" data-category="food">🍽️</span>
					<span class="emoji" data-category="food">🥣</span>
					<span class="emoji" data-category="food">🥡</span>
					<span class="emoji" data-category="food">🥢</span>
					<span class="emoji" data-category="food">🧂</span>

					
					
<!-----------------------------------Foods End--------------------------------------------------------------------------------->



<!-----------------------------------Sports Start ------------------------------------------------------------------------>

					<span class="emoji" data-category="sports">⚽</span>
					<span class="emoji" data-category="sports">🏀</span>
					<span class="emoji" data-category="sports">🏈</span>
					<span class="emoji" data-category="sports">⚾</span>
					<span class="emoji" data-category="sports">🥎</span>
					<span class="emoji" data-category="sports">🎾</span>
					<span class="emoji" data-category="sports">🏐</span>
					<span class="emoji" data-category="sports">🏉</span>
					<span class="emoji" data-category="sports">🥏</span>
					<span class="emoji" data-category="sports">🎱</span>
					<span class="emoji" data-category="sports">🪀</span>
					<span class="emoji" data-category="sports">🏓</span>
					<span class="emoji" data-category="sports">🏸</span>
					<span class="emoji" data-category="sports">🏒</span>
					<span class="emoji" data-category="sports">🏑</span>
					<span class="emoji" data-category="sports">🥍</span>
					<span class="emoji" data-category="sports">🏏</span>
					<span class="emoji" data-category="sports">🪃</span>
					<span class="emoji" data-category="sports">🥅</span>
					<span class="emoji" data-category="sports">⛳</span>
					<span class="emoji" data-category="sports">🪁</span>
					<span class="emoji" data-category="sports">🏹</span>
					<span class="emoji" data-category="sports">🎣</span>
					<span class="emoji" data-category="sports">🤿</span>
					<span class="emoji" data-category="sports">🥊</span>
					<span class="emoji" data-category="sports">🥋</span>
					<span class="emoji" data-category="sports">🎽</span>
					<span class="emoji" data-category="sports">🛹</span>
					<span class="emoji" data-category="sports">🛼</span>
					<span class="emoji" data-category="sports">🛷</span>
					<span class="emoji" data-category="sports">⛸️</span>
					<span class="emoji" data-category="sports">🥌</span>
					<span class="emoji" data-category="sports">🎿</span>
					<span class="emoji" data-category="sports">⛷️</span>
					<span class="emoji" data-category="sports">🏂</span>
					<span class="emoji" data-category="sports">🪂</span>
					<span class="emoji" data-category="sports">🤼‍♀️</span>
					<span class="emoji" data-category="sports">🏋🏻‍♀️</span>
					<span class="emoji" data-category="sports">🏋🏻‍♂️</span>
					<span class="emoji" data-category="sports">🤼‍♂️</span>
					<span class="emoji" data-category="sports">🤸🏻‍♀️</span>
					<span class="emoji" data-category="sports">🤸🏻‍♂️</span>
					<span class="emoji" data-category="sports">⛹🏻‍♀️</span>
					<span class="emoji" data-category="sports">⛹️‍♂️</span>
					<span class="emoji" data-category="sports">🤺</span>
					<span class="emoji" data-category="sports">🤾🏻‍♀️</span>
					<span class="emoji" data-category="sports">🤾🏻‍♂️</span>
					<span class="emoji" data-category="sports">🏌️‍♀️</span>
					<span class="emoji" data-category="sports">🏌🏻‍♂️</span>
					<span class="emoji" data-category="sports">🏇🏻</span>
					<span class="emoji" data-category="sports">🧘🏻‍♀️</span>
					<span class="emoji" data-category="sports">🧘🏻‍♂️</span>
					<span class="emoji" data-category="sports">🏄🏻‍♀️</span>
					<span class="emoji" data-category="sports">🏄🏻‍♂️</span>
					<span class="emoji" data-category="sports">🏊🏻‍♀️</span>
					<span class="emoji" data-category="sports">🏊🏻‍♂️</span>
					<span class="emoji" data-category="sports">🤽🏻‍♀️</span>
					<span class="emoji" data-category="sports">🤽🏻‍♂️</span>
					<span class="emoji" data-category="sports">🚣🏻‍♀️</span>
					<span class="emoji" data-category="sports">🚣🏻‍♂️</span>
					<span class="emoji" data-category="sports">🧗🏻‍♀️</span>
					<span class="emoji" data-category="sports">🧗🏻‍♂️</span>
					<span class="emoji" data-category="sports">🚵🏻‍♀️</span>
					<span class="emoji" data-category="sports">🚵🏻‍♂️</span>
					<span class="emoji" data-category="sports">🚴🏻‍♀️</span>
					<span class="emoji" data-category="sports">🚴🏻‍♂️</span>
					<span class="emoji" data-category="sports">🏆</span>
					<span class="emoji" data-category="sports">🥇</span>
					<span class="emoji" data-category="sports">🥈</span>
					<span class="emoji" data-category="sports">🥉</span>
					<span class="emoji" data-category="sports">🏅</span>
					<span class="emoji" data-category="sports">🎖️</span>
					<span class="emoji" data-category="sports">🏵️</span>
					<span class="emoji" data-category="sports">🎗️</span>
					<span class="emoji" data-category="sports">🎫</span>
					<span class="emoji" data-category="sports">🎟️</span>
					<span class="emoji" data-category="sports">🎪</span>
					<span class="emoji" data-category="sports">🤹🏻‍♀️</span>
					<span class="emoji" data-category="sports">🤹🏻‍♂️</span>
					<span class="emoji" data-category="sports">🎭</span>
					<span class="emoji" data-category="sports">🩰</span>
					<span class="emoji" data-category="sports">🎨</span>
					<span class="emoji" data-category="sports">🎬</span>
					<span class="emoji" data-category="sports">🎤</span>
					<span class="emoji" data-category="sports">🎧</span>
					<span class="emoji" data-category="sports">🎼</span>
					<span class="emoji" data-category="sports">🎹</span>
					<span class="emoji" data-category="sports">🥁</span>
					<span class="emoji" data-category="sports">🪘</span>
					<span class="emoji" data-category="sports">🎷</span>
					<span class="emoji" data-category="sports">🎺</span>
					<span class="emoji" data-category="sports">🪗</span>
					<span class="emoji" data-category="sports">🎸</span>
					<span class="emoji" data-category="sports">🪕</span>
					<span class="emoji" data-category="sports">🎻</span>
					<span class="emoji" data-category="sports">🎲</span>
					<span class="emoji" data-category="sports">♟️</span>
					<span class="emoji" data-category="sports">🎯</span>
					<span class="emoji" data-category="sports">🎳</span>
					<span class="emoji" data-category="sports">🎮</span>
					<span class="emoji" data-category="sports">🎰</span>
					<span class="emoji" data-category="sports">🧩</span>

<!----------------------------------Sports End---------------------------------------------------------------------------------->




<!----------------------------------Vehicles & Places Start------------------------------------------------------------------------>

					<span class="emoji" data-category="vehicles-places">🚗</span>
					<span class="emoji" data-category="vehicles-places">🚕</span>
					<span class="emoji" data-category="vehicles-places">🚙</span>
					<span class="emoji" data-category="vehicles-places">🚌</span>
					<span class="emoji" data-category="vehicles-places">🚎</span>
					<span class="emoji" data-category="vehicles-places">🏎️</span>
					<span class="emoji" data-category="vehicles-places">🚓</span>
					<span class="emoji" data-category="vehicles-places">🚑</span>
					<span class="emoji" data-category="vehicles-places">🚒</span>
					<span class="emoji" data-category="vehicles-places">🚐</span>
					<span class="emoji" data-category="vehicles-places">🛻</span>
					<span class="emoji" data-category="vehicles-places">🚚</span>
					<span class="emoji" data-category="vehicles-places">🚛</span>
					<span class="emoji" data-category="vehicles-places">🚜</span>
					<span class="emoji" data-category="vehicles-places">🦯</span>
					<span class="emoji" data-category="vehicles-places">🦽</span>
					<span class="emoji" data-category="vehicles-places">🦼</span>
					<span class="emoji" data-category="vehicles-places">🛴</span>
					<span class="emoji" data-category="vehicles-places">🚲</span>
					<span class="emoji" data-category="vehicles-places">🛵</span>
					<span class="emoji" data-category="vehicles-places">🏍️</span>
					<span class="emoji" data-category="vehicles-places">🛺</span>
					<span class="emoji" data-category="vehicles-places">🚨</span>
					<span class="emoji" data-category="vehicles-places">🚔</span>
					<span class="emoji" data-category="vehicles-places">🚍</span>
					<span class="emoji" data-category="vehicles-places">🚘</span>
					<span class="emoji" data-category="vehicles-places">🚖</span>
					<span class="emoji" data-category="vehicles-places">🚡</span>
					<span class="emoji" data-category="vehicles-places">🚠</span>
					<span class="emoji" data-category="vehicles-places">🚟</span>
					<span class="emoji" data-category="vehicles-places">🚃</span>
					<span class="emoji" data-category="vehicles-places">🚋</span>
					<span class="emoji" data-category="vehicles-places">🚞</span>
					<span class="emoji" data-category="vehicles-places">🚝</span>
					<span class="emoji" data-category="vehicles-places">🚄</span>
					<span class="emoji" data-category="vehicles-places">🚅</span>
					<span class="emoji" data-category="vehicles-places">🚈</span>
					<span class="emoji" data-category="vehicles-places">🚂</span>
					<span class="emoji" data-category="vehicles-places">🚆</span>
					<span class="emoji" data-category="vehicles-places">🚇</span>
					<span class="emoji" data-category="vehicles-places">🚊</span>
					<span class="emoji" data-category="vehicles-places">🚉</span>
					<span class="emoji" data-category="vehicles-places">✈️</span>
					<span class="emoji" data-category="vehicles-places">🛫</span>
					<span class="emoji" data-category="vehicles-places">🛬</span>
					<span class="emoji" data-category="vehicles-places">🛩️</span>
					<span class="emoji" data-category="vehicles-places">💺</span>
					<span class="emoji" data-category="vehicles-places">🛰️</span>
					<span class="emoji" data-category="vehicles-places">🚀</span>
					<span class="emoji" data-category="vehicles-places">🛸</span>
					<span class="emoji" data-category="vehicles-places">🚁</span>
					<span class="emoji" data-category="vehicles-places">🛶</span>
					<span class="emoji" data-category="vehicles-places">⛵</span>
					<span class="emoji" data-category="vehicles-places">🚤</span>
					<span class="emoji" data-category="vehicles-places">🛥️</span>
					<span class="emoji" data-category="vehicles-places">🛳️</span>
					<span class="emoji" data-category="vehicles-places">⛴️</span>
					<span class="emoji" data-category="vehicles-places">🚢</span>
					<span class="emoji" data-category="vehicles-places">⚓</span>
					<span class="emoji" data-category="vehicles-places">🪝</span>
					<span class="emoji" data-category="vehicles-places">⛽</span>
					<span class="emoji" data-category="vehicles-places">🚧</span>
					<span class="emoji" data-category="vehicles-places">🚦</span>
					<span class="emoji" data-category="vehicles-places">🚥</span>
					<span class="emoji" data-category="vehicles-places">🚏</span>
					<span class="emoji" data-category="vehicles-places">🗺️</span>
					<span class="emoji" data-category="vehicles-places">🗿</span>
					<span class="emoji" data-category="vehicles-places">🗽</span>
					<span class="emoji" data-category="vehicles-places">🗼</span>
					<span class="emoji" data-category="vehicles-places">🏰</span>
					<span class="emoji" data-category="vehicles-places">🏯</span>
					<span class="emoji" data-category="vehicles-places">🏟️</span>
					<span class="emoji" data-category="vehicles-places">🎡</span>
					<span class="emoji" data-category="vehicles-places">🎢</span>
					<span class="emoji" data-category="vehicles-places">🎠</span>
					<span class="emoji" data-category="vehicles-places">⛲</span>
					<span class="emoji" data-category="vehicles-places">⛱️</span>
					<span class="emoji" data-category="vehicles-places">🏖️</span>
					<span class="emoji" data-category="vehicles-places">🏝️</span>
					<span class="emoji" data-category="vehicles-places">🏜️</span>
					<span class="emoji" data-category="vehicles-places">🌋</span>
					<span class="emoji" data-category="vehicles-places">⛰️</span>
					<span class="emoji" data-category="vehicles-places">🗻</span>
					<span class="emoji" data-category="vehicles-places">🏕️</span>
					<span class="emoji" data-category="vehicles-places">⛺</span>
					<span class="emoji" data-category="vehicles-places">🛖</span>
					<span class="emoji" data-category="vehicles-places">🏠</span>
					<span class="emoji" data-category="vehicles-places">🏡</span>
					<span class="emoji" data-category="vehicles-places">🏘️</span>
					<span class="emoji" data-category="vehicles-places">🏚️</span>
					<span class="emoji" data-category="vehicles-places">🏗️</span>
					<span class="emoji" data-category="vehicles-places">🏭</span>
					<span class="emoji" data-category="vehicles-places">🏢</span>
					<span class="emoji" data-category="vehicles-places">🏬</span>
					<span class="emoji" data-category="vehicles-places">🏣</span>
					<span class="emoji" data-category="vehicles-places">🏤</span>
					<span class="emoji" data-category="vehicles-places">🏥</span>
					<span class="emoji" data-category="vehicles-places">🏦</span>
					<span class="emoji" data-category="vehicles-places">🏨</span>
					<span class="emoji" data-category="vehicles-places">🏪</span>
					<span class="emoji" data-category="vehicles-places">🏫</span>
					<span class="emoji" data-category="vehicles-places">🏩</span>
					<span class="emoji" data-category="vehicles-places">💒</span>
					<span class="emoji" data-category="vehicles-places">🏛️</span>
					<span class="emoji" data-category="vehicles-places">⛪</span>
					<span class="emoji" data-category="vehicles-places">🕌</span>
					<span class="emoji" data-category="vehicles-places">🕍</span>
					<span class="emoji" data-category="vehicles-places">⛩️</span>
					<span class="emoji" data-category="vehicles-places">🛤️</span>
					<span class="emoji" data-category="vehicles-places">🛣️</span>
					<span class="emoji" data-category="vehicles-places">🗾</span>
					<span class="emoji" data-category="vehicles-places">🎑</span>
					<span class="emoji" data-category="vehicles-places">🏞️</span>
					<span class="emoji" data-category="vehicles-places">🌅</span>
					<span class="emoji" data-category="vehicles-places">🌄</span>
					<span class="emoji" data-category="vehicles-places">🌠</span>
					<span class="emoji" data-category="vehicles-places">🎇</span>
					<span class="emoji" data-category="vehicles-places">🎆</span>
					<span class="emoji" data-category="vehicles-places">🌇</span>
					<span class="emoji" data-category="vehicles-places">🌆</span>
					<span class="emoji" data-category="vehicles-places">🏙️</span>
					<span class="emoji" data-category="vehicles-places">🌃</span>
					<span class="emoji" data-category="vehicles-places">🌌</span>
					<span class="emoji" data-category="vehicles-places">🌉</span>


<!----------------------------------Vehicles & Places End ------------------------------------------------------------------------->





<!----------------------------------Tools & Accessories ----------------------------------------------------------------------->

					<span class="emoji" data-category="tools-accessories">⌚</span>
					<span class="emoji" data-category="tools-accessories">📱</span>
					<span class="emoji" data-category="tools-accessories">📲</span>
					<span class="emoji" data-category="tools-accessories">💻</span>
					<span class="emoji" data-category="tools-accessories">⌨️</span>
					<span class="emoji" data-category="tools-accessories">🖥️</span>
					<span class="emoji" data-category="tools-accessories">🖨️</span>
					<span class="emoji" data-category="tools-accessories">🖱️</span>
					<span class="emoji" data-category="tools-accessories">🖲️</span>
					<span class="emoji" data-category="tools-accessories">🕹️</span>
					<span class="emoji" data-category="tools-accessories">🗜️</span>
					<span class="emoji" data-category="tools-accessories">💽</span>
					<span class="emoji" data-category="tools-accessories">💾</span>
					<span class="emoji" data-category="tools-accessories">💿</span>
					<span class="emoji" data-category="tools-accessories">📀</span>
					<span class="emoji" data-category="tools-accessories">📼</span>
					<span class="emoji" data-category="tools-accessories">📷</span>
					<span class="emoji" data-category="tools-accessories">📸</span>
					<span class="emoji" data-category="tools-accessories">📹</span>
					<span class="emoji" data-category="tools-accessories">🎥</span>
					<span class="emoji" data-category="tools-accessories">📽️</span>
					<span class="emoji" data-category="tools-accessories">🎞️</span>
					<span class="emoji" data-category="tools-accessories">📞</span>
					<span class="emoji" data-category="tools-accessories">☎️</span>
					<span class="emoji" data-category="tools-accessories">📟</span>
					<span class="emoji" data-category="tools-accessories">📠</span>
					<span class="emoji" data-category="tools-accessories">📺</span>
					<span class="emoji" data-category="tools-accessories">📻</span>
					<span class="emoji" data-category="tools-accessories">🎙️</span>
					<span class="emoji" data-category="tools-accessories">🎚️</span>
					<span class="emoji" data-category="tools-accessories">🎛️</span>
					<span class="emoji" data-category="tools-accessories">🧭</span>
					<span class="emoji" data-category="tools-accessories">⏱️</span>
					<span class="emoji" data-category="tools-accessories">⏲️</span>
					<span class="emoji" data-category="tools-accessories">⏰</span>
					<span class="emoji" data-category="tools-accessories">⌛</span>
					<span class="emoji" data-category="tools-accessories">⏳</span>
					<span class="emoji" data-category="tools-accessories">📡</span>
					<span class="emoji" data-category="tools-accessories">🔋</span>
					<span class="emoji" data-category="tools-accessories">🔌</span>
					<span class="emoji" data-category="tools-accessories">💡</span>
					<span class="emoji" data-category="tools-accessories">🔦</span>
					<span class="emoji" data-category="tools-accessories">🕯️</span>
					<span class="emoji" data-category="tools-accessories">🪔</span>
					<span class="emoji" data-category="tools-accessories">🧯</span>
					<span class="emoji" data-category="tools-accessories">🛢️</span>
					<span class="emoji" data-category="tools-accessories">💸</span>
					<span class="emoji" data-category="tools-accessories">💵</span>
					<span class="emoji" data-category="tools-accessories">💴</span>
					<span class="emoji" data-category="tools-accessories">💶</span>
					<span class="emoji" data-category="tools-accessories">💷</span>
					<span class="emoji" data-category="tools-accessories">🪙</span>
					<span class="emoji" data-category="tools-accessories">💰</span>
					<span class="emoji" data-category="tools-accessories">💳</span>
					<span class="emoji" data-category="tools-accessories">💎</span>
					<span class="emoji" data-category="tools-accessories">⚖️</span>
					<span class="emoji" data-category="tools-accessories">🪜</span>
					<span class="emoji" data-category="tools-accessories">🧰</span>
					<span class="emoji" data-category="tools-accessories">🪛</span>
					<span class="emoji" data-category="tools-accessories">🔧</span>
					<span class="emoji" data-category="tools-accessories">🔨</span>
					<span class="emoji" data-category="tools-accessories">⚒️</span>
					<span class="emoji" data-category="tools-accessories">🛠️</span>
					<span class="emoji" data-category="tools-accessories">⛏️</span>
					<span class="emoji" data-category="tools-accessories">🪚</span>
					<span class="emoji" data-category="tools-accessories">🔩</span>
					<span class="emoji" data-category="tools-accessories">⚙️</span>
					<span class="emoji" data-category="tools-accessories">🪤</span>
					<span class="emoji" data-category="tools-accessories">🧱</span>
					<span class="emoji" data-category="tools-accessories">⛓️</span>
					<span class="emoji" data-category="tools-accessories">🧲</span>
					<span class="emoji" data-category="tools-accessories">🔫</span>
					<span class="emoji" data-category="tools-accessories">💣</span>
					<span class="emoji" data-category="tools-accessories">🧨</span>
					<span class="emoji" data-category="tools-accessories">🪓</span>
					<span class="emoji" data-category="tools-accessories">🔪</span>
					<span class="emoji" data-category="tools-accessories">🗡️</span>
					<span class="emoji" data-category="tools-accessories">⚔️</span>
					<span class="emoji" data-category="tools-accessories">🛡️</span>
					<span class="emoji" data-category="tools-accessories">🚬</span>
					<span class="emoji" data-category="tools-accessories">⚰️</span>
					<span class="emoji" data-category="tools-accessories">🪦</span>
					<span class="emoji" data-category="tools-accessories">⚱️</span>
					<span class="emoji" data-category="tools-accessories">🏺</span>
					<span class="emoji" data-category="tools-accessories">🔮</span>
					<span class="emoji" data-category="tools-accessories">📿</span>
					<span class="emoji" data-category="tools-accessories">🧿</span>
					<span class="emoji" data-category="tools-accessories">💈</span>
					<span class="emoji" data-category="tools-accessories">⚗️</span>
					<span class="emoji" data-category="tools-accessories">🔭</span>
					<span class="emoji" data-category="tools-accessories">🔬</span>
					<span class="emoji" data-category="tools-accessories">🕳️</span>
					<span class="emoji" data-category="tools-accessories">🩹</span>
					<span class="emoji" data-category="tools-accessories">🩺</span>
					<span class="emoji" data-category="tools-accessories">💊</span>
					<span class="emoji" data-category="tools-accessories">💉</span>
					<span class="emoji" data-category="tools-accessories">🩸</span>
					<span class="emoji" data-category="tools-accessories">🧬</span>
					<span class="emoji" data-category="tools-accessories">🦠</span>
					<span class="emoji" data-category="tools-accessories">🧫</span>
					<span class="emoji" data-category="tools-accessories">🧪</span>
					<span class="emoji" data-category="tools-accessories">🌡️</span>
					<span class="emoji" data-category="tools-accessories">🧹</span>
					<span class="emoji" data-category="tools-accessories">🪠</span>
					<span class="emoji" data-category="tools-accessories">🧺</span>
					<span class="emoji" data-category="tools-accessories">🚽</span>
					<span class="emoji" data-category="tools-accessories">🚰</span>
					<span class="emoji" data-category="tools-accessories">🚿</span>
					<span class="emoji" data-category="tools-accessories">🛁</span>
					<span class="emoji" data-category="tools-accessories">🛀</span>
					<span class="emoji" data-category="tools-accessories">🪥</span>
					<span class="emoji" data-category="tools-accessories">🪒</span>
					<span class="emoji" data-category="tools-accessories">🧽</span>
					<span class="emoji" data-category="tools-accessories">🪣</span>
					<span class="emoji" data-category="tools-accessories">🧴</span>
					<span class="emoji" data-category="tools-accessories">🛎️</span>
					<span class="emoji" data-category="tools-accessories">🔑</span>
					<span class="emoji" data-category="tools-accessories">🗝️</span>
					<span class="emoji" data-category="tools-accessories">🚪</span>
					<span class="emoji" data-category="tools-accessories">🪑</span>
					<span class="emoji" data-category="tools-accessories">🛋️</span>
					<span class="emoji" data-category="tools-accessories">🛏️</span>
					<span class="emoji" data-category="tools-accessories">🛌🏻</span>
					<span class="emoji" data-category="tools-accessories">🧸</span>
					<span class="emoji" data-category="tools-accessories">🪆</span>
					<span class="emoji" data-category="tools-accessories">🖼️</span>
					<span class="emoji" data-category="tools-accessories">🪞</span>
					<span class="emoji" data-category="tools-accessories">🪟</span>
					<span class="emoji" data-category="tools-accessories">🛍️</span>
					<span class="emoji" data-category="tools-accessories">🛒</span>
					<span class="emoji" data-category="tools-accessories">🎁</span>
					<span class="emoji" data-category="tools-accessories">🎈</span>
					<span class="emoji" data-category="tools-accessories">🎏</span>
					<span class="emoji" data-category="tools-accessories">🎀</span>
					<span class="emoji" data-category="tools-accessories">🪄</span>
					<span class="emoji" data-category="tools-accessories">🪅</span>
					<span class="emoji" data-category="tools-accessories">🎊</span>
					<span class="emoji" data-category="tools-accessories">🎉</span>
					<span class="emoji" data-category="tools-accessories">🎎</span>
					<span class="emoji" data-category="tools-accessories">🪭</span>
					<span class="emoji" data-category="tools-accessories">🏮</span>
					<span class="emoji" data-category="tools-accessories">🎐</span>
					<span class="emoji" data-category="tools-accessories">🧧</span>
					<span class="emoji" data-category="tools-accessories">✉️</span>
					<span class="emoji" data-category="tools-accessories">📩</span>
					<span class="emoji" data-category="tools-accessories">📨</span>
					<span class="emoji" data-category="tools-accessories">📧</span>
					<span class="emoji" data-category="tools-accessories">💌</span>
					<span class="emoji" data-category="tools-accessories">📥</span>
					<span class="emoji" data-category="tools-accessories">📤</span>
					<span class="emoji" data-category="tools-accessories">📦</span>
					<span class="emoji" data-category="tools-accessories">🏷️</span>
					<span class="emoji" data-category="tools-accessories">🪧</span>
					<span class="emoji" data-category="tools-accessories">📪</span>
					<span class="emoji" data-category="tools-accessories">📫</span>
					<span class="emoji" data-category="tools-accessories">📬</span>
					<span class="emoji" data-category="tools-accessories">📭</span>
					<span class="emoji" data-category="tools-accessories">📯</span>
					<span class="emoji" data-category="tools-accessories">📜</span>
					<span class="emoji" data-category="tools-accessories">📃</span>
					<span class="emoji" data-category="tools-accessories">📄</span>
					<span class="emoji" data-category="tools-accessories">📑</span>
					<span class="emoji" data-category="tools-accessories">🧾</span>
					<span class="emoji" data-category="tools-accessories">📊</span>
					<span class="emoji" data-category="tools-accessories">📈</span>
					<span class="emoji" data-category="tools-accessories">📉</span>
					<span class="emoji" data-category="tools-accessories">🗒️</span>
					<span class="emoji" data-category="tools-accessories">🗓️</span>
					<span class="emoji" data-category="tools-accessories">📆</span>
					<span class="emoji" data-category="tools-accessories">📅</span>
					<span class="emoji" data-category="tools-accessories">🗑️</span>
					<span class="emoji" data-category="tools-accessories">📇</span>
					<span class="emoji" data-category="tools-accessories">🗃️</span>
					<span class="emoji" data-category="tools-accessories">🗳️</span>
					<span class="emoji" data-category="tools-accessories">🗄️</span>
					<span class="emoji" data-category="tools-accessories">📋</span>
					<span class="emoji" data-category="tools-accessories">📁</span>
					<span class="emoji" data-category="tools-accessories">📂</span>
					<span class="emoji" data-category="tools-accessories">🗂️</span>
					<span class="emoji" data-category="tools-accessories">🗞️</span>
					<span class="emoji" data-category="tools-accessories">📰</span>
					<span class="emoji" data-category="tools-accessories">📓</span>
					<span class="emoji" data-category="tools-accessories">📔</span>
					<span class="emoji" data-category="tools-accessories">📒</span>
					<span class="emoji" data-category="tools-accessories">📕</span>
					<span class="emoji" data-category="tools-accessories">📗</span>
					<span class="emoji" data-category="tools-accessories">📘</span>
					<span class="emoji" data-category="tools-accessories">📙</span>
					<span class="emoji" data-category="tools-accessories">📚</span>
					<span class="emoji" data-category="tools-accessories">📖</span>
					<span class="emoji" data-category="tools-accessories">🔖</span>
					<span class="emoji" data-category="tools-accessories">🧷</span>
					<span class="emoji" data-category="tools-accessories">🔗</span>
					<span class="emoji" data-category="tools-accessories">📎</span>
					<span class="emoji" data-category="tools-accessories">🖇️</span>
					<span class="emoji" data-category="tools-accessories">📐</span>
					<span class="emoji" data-category="tools-accessories">📏</span>
					<span class="emoji" data-category="tools-accessories">🧮</span>
					<span class="emoji" data-category="tools-accessories">📌</span>
					<span class="emoji" data-category="tools-accessories">📍</span>
					<span class="emoji" data-category="tools-accessories">✂️</span>
					<span class="emoji" data-category="tools-accessories">🖊️</span>
					<span class="emoji" data-category="tools-accessories">🖋️</span>
					<span class="emoji" data-category="tools-accessories">✒️</span>
					<span class="emoji" data-category="tools-accessories">🖌️</span>
					<span class="emoji" data-category="tools-accessories">🖍️</span>
					<span class="emoji" data-category="tools-accessories">📝</span>
					<span class="emoji" data-category="tools-accessories">✏️</span>
					<span class="emoji" data-category="tools-accessories">🔍</span>
					<span class="emoji" data-category="tools-accessories">🔎</span>
					<span class="emoji" data-category="tools-accessories">🔏</span>
					<span class="emoji" data-category="tools-accessories">🔐</span>
					<span class="emoji" data-category="tools-accessories">🔒</span>
					<span class="emoji" data-category="tools-accessories">🔓</span>


<!---------------------------------Tools & Accessories End----------------------------------------------------------------------->



<!----------------------------------Signs Start ---------------------------------------------------------------------------->

			
					<span class="emoji" data-category="signs">❤️</span>
					<span class="emoji" data-category="signs">🧡</span>
					<span class="emoji" data-category="signs">💛</span>
					<span class="emoji" data-category="signs">💚</span>
					<span class="emoji" data-category="signs">💙</span>
					<span class="emoji" data-category="signs">💜</span>
					<span class="emoji" data-category="signs">🖤</span>
					<span class="emoji" data-category="signs">🤍</span>
					<span class="emoji" data-category="signs">🤎</span>
					<span class="emoji" data-category="signs">💔</span>
					<span class="emoji" data-category="signs">❤️‍🔥</span>
					<span class="emoji" data-category="signs">❤️‍🩹</span>
					<span class="emoji" data-category="signs">❣️</span>
					<span class="emoji" data-category="signs">💕</span>
					<span class="emoji" data-category="signs">💞</span>
					<span class="emoji" data-category="signs">💓</span>
					<span class="emoji" data-category="signs">💗</span>
					<span class="emoji" data-category="signs">💖</span>
					<span class="emoji" data-category="signs">💘</span>
					<span class="emoji" data-category="signs">💝</span>
					<span class="emoji" data-category="signs">💟</span>
					<span class="emoji" data-category="signs">☮️</span>
					<span class="emoji" data-category="signs">✝️</span>
					<span class="emoji" data-category="signs">☪️</span>
					<span class="emoji" data-category="signs">🕉️</span>
					<span class="emoji" data-category="signs">☸️</span>
					<span class="emoji" data-category="signs">✡️</span>
					<span class="emoji" data-category="signs">🔯</span>
					<span class="emoji" data-category="signs">🕎</span>
					<span class="emoji" data-category="signs">☯️</span>
					<span class="emoji" data-category="signs">☦️</span>
					<span class="emoji" data-category="signs">🛐</span>
					<span class="emoji" data-category="signs">⛎</span>
					<span class="emoji" data-category="signs">♈</span>
					<span class="emoji" data-category="signs">♉</span>
					<span class="emoji" data-category="signs">♊</span>
					<span class="emoji" data-category="signs">♋</span>
					<span class="emoji" data-category="signs">♌</span>
					<span class="emoji" data-category="signs">♍</span>
					<span class="emoji" data-category="signs">♎</span>
					<span class="emoji" data-category="signs">♏</span>
					<span class="emoji" data-category="signs">♐</span>
					<span class="emoji" data-category="signs">♑</span>
					<span class="emoji" data-category="signs">♒</span>
					<span class="emoji" data-category="signs">♓</span>
					<span class="emoji" data-category="signs">🆔</span>
					<span class="emoji" data-category="signs">⚛️</span>
					<span class="emoji" data-category="signs">🉑</span>
					<span class="emoji" data-category="signs">☢️</span>
					<span class="emoji" data-category="signs">☣️</span>
					<span class="emoji" data-category="signs">📴</span>
					<span class="emoji" data-category="signs">📳</span>
					<span class="emoji" data-category="signs">🈶</span>
					<span class="emoji" data-category="signs">🈚</span>
					<span class="emoji" data-category="signs">🈸</span>
					<span class="emoji" data-category="signs">🈺</span>
					<span class="emoji" data-category="signs">🈷️</span>
					<span class="emoji" data-category="signs">✴️</span>
					<span class="emoji" data-category="signs">🆚</span>
					<span class="emoji" data-category="signs">💮</span>
					<span class="emoji" data-category="signs">🉐</span>
					<span class="emoji" data-category="signs">㊙️</span>
					<span class="emoji" data-category="signs">㊗️</span>
					<span class="emoji" data-category="signs">🈴</span>
					<span class="emoji" data-category="signs">🈵</span>
					<span class="emoji" data-category="signs">🈹</span>
					<span class="emoji" data-category="signs">🈲</span>
					<span class="emoji" data-category="signs">🅰️</span>
					<span class="emoji" data-category="signs">🅱️</span>
					<span class="emoji" data-category="signs">🆎</span>
					<span class="emoji" data-category="signs">🆑</span>
					<span class="emoji" data-category="signs">🅾️</span>
					<span class="emoji" data-category="signs">🆘</span>
					<span class="emoji" data-category="signs">❌</span>
					<span class="emoji" data-category="signs">⭕</span>
					<span class="emoji" data-category="signs">🛑</span>
					<span class="emoji" data-category="signs">⛔</span>
					<span class="emoji" data-category="signs">📛</span>
					<span class="emoji" data-category="signs">🚫</span>
					<span class="emoji" data-category="signs">💯</span>
					<span class="emoji" data-category="signs">💢</span>
					<span class="emoji" data-category="signs">♨️</span>
					<span class="emoji" data-category="signs">🚷</span>
					<span class="emoji" data-category="signs">🚯</span>
					<span class="emoji" data-category="signs">🚳</span>
					<span class="emoji" data-category="signs">🚱</span>
					<span class="emoji" data-category="signs">🔞</span>
					<span class="emoji" data-category="signs">📵</span>
					<span class="emoji" data-category="signs">🚭</span>
					<span class="emoji" data-category="signs">❗</span>
					<span class="emoji" data-category="signs">❕</span>
					<span class="emoji" data-category="signs">❓</span>
					<span class="emoji" data-category="signs">❔</span>
					<span class="emoji" data-category="signs">‼️</span>
					<span class="emoji" data-category="signs">⁉️</span>
					<span class="emoji" data-category="signs">🔅</span>
					<span class="emoji" data-category="signs">🔆</span>
					<span class="emoji" data-category="signs">〽️</span>
					<span class="emoji" data-category="signs">⚠️</span>
					<span class="emoji" data-category="signs">🚸</span>
					<span class="emoji" data-category="signs">🔱</span>
					<span class="emoji" data-category="signs">⚜️</span>
					<span class="emoji" data-category="signs">🔰</span>
					<span class="emoji" data-category="signs">♻️</span>
					<span class="emoji" data-category="signs">✅</span>
					<span class="emoji" data-category="signs">🈯</span>
					<span class="emoji" data-category="signs">💹</span>
					<span class="emoji" data-category="signs">❇️</span>
					<span class="emoji" data-category="signs">✳️</span>
					<span class="emoji" data-category="signs">❎</span>
					<span class="emoji" data-category="signs">🌐</span>
					<span class="emoji" data-category="signs">💠</span>
					<span class="emoji" data-category="signs">Ⓜ️</span>
					<span class="emoji" data-category="signs">🌀</span>
					<span class="emoji" data-category="signs">💤</span>
					<span class="emoji" data-category="signs">🏧</span>
					<span class="emoji" data-category="signs">🚾</span>
					<span class="emoji" data-category="signs">♿</span>
					<span class="emoji" data-category="signs">🅿️</span>
					<span class="emoji" data-category="signs">🛗</span>
					<span class="emoji" data-category="signs">🈳</span>
					<span class="emoji" data-category="signs">🈂️</span>
					<span class="emoji" data-category="signs">🛂</span>
					<span class="emoji" data-category="signs">🛃</span>
					<span class="emoji" data-category="signs">🛄</span>
					<span class="emoji" data-category="signs">🛅</span>
					<span class="emoji" data-category="signs">🚹</span>
					<span class="emoji" data-category="signs">🚺</span>
					<span class="emoji" data-category="signs">🚼</span>
					<span class="emoji" data-category="signs">⚧</span>
					<span class="emoji" data-category="signs">🚻</span>
					<span class="emoji" data-category="signs">🚮</span>
					<span class="emoji" data-category="signs">🎦</span>
					<span class="emoji" data-category="signs">📶</span>
					<span class="emoji" data-category="signs">🈁</span>
					<span class="emoji" data-category="signs">🔣</span>
					<span class="emoji" data-category="signs">ℹ️</span>
					<span class="emoji" data-category="signs">🔤</span>
					<span class="emoji" data-category="signs">🔡</span>
					<span class="emoji" data-category="signs">🔠</span>
					<span class="emoji" data-category="signs">🆖</span>
					<span class="emoji" data-category="signs">🆗</span>
					<span class="emoji" data-category="signs">🆙</span>
					<span class="emoji" data-category="signs">🆒</span>
					<span class="emoji" data-category="signs">🆕</span>
					<span class="emoji" data-category="signs">🆓</span>
					<span class="emoji" data-category="signs">0️⃣</span>
					<span class="emoji" data-category="signs">1️⃣</span>
					<span class="emoji" data-category="signs">2️⃣</span>
					<span class="emoji" data-category="signs">3️⃣</span>
					<span class="emoji" data-category="signs">4️⃣</span>
					<span class="emoji" data-category="signs">5️⃣</span>
					<span class="emoji" data-category="signs">6️⃣</span>
					<span class="emoji" data-category="signs">7️⃣</span>
					<span class="emoji" data-category="signs">8️⃣</span>
					<span class="emoji" data-category="signs">9️⃣</span>
					<span class="emoji" data-category="signs">🔟</span>
					<span class="emoji" data-category="signs">#️⃣</span>
					<span class="emoji" data-category="signs">*️⃣</span>
					<span class="emoji" data-category="signs">⏏️</span>
					<span class="emoji" data-category="signs">▶️</span>
					<span class="emoji" data-category="signs">⏸️</span>
					<span class="emoji" data-category="signs">⏯️</span>
					<span class="emoji" data-category="signs">⏹️</span>
					<span class="emoji" data-category="signs">⏺️</span>
					<span class="emoji" data-category="signs">⏭️</span>
					<span class="emoji" data-category="signs">⏮️</span>
					<span class="emoji" data-category="signs">⏩</span>
					<span class="emoji" data-category="signs">⏪</span>
					<span class="emoji" data-category="signs">⏫</span>
					<span class="emoji" data-category="signs">⏬</span>
					<span class="emoji" data-category="signs">◀️</span>
					<span class="emoji" data-category="signs">🔼</span>
					<span class="emoji" data-category="signs">🔽</span>
					<span class="emoji" data-category="signs">➡️</span>
					<span class="emoji" data-category="signs">⬅️</span>
					<span class="emoji" data-category="signs">⬆️</span>
					<span class="emoji" data-category="signs">⬇️</span>
					<span class="emoji" data-category="signs">↗️</span>
					<span class="emoji" data-category="signs">↘️</span>
					<span class="emoji" data-category="signs">↙️</span>
					<span class="emoji" data-category="signs">↖️</span>
					<span class="emoji" data-category="signs">↕️</span>
					<span class="emoji" data-category="signs">↔️</span>
					<span class="emoji" data-category="signs">↪️</span>
					<span class="emoji" data-category="signs">↩️</span>
					<span class="emoji" data-category="signs">⤴️</span>
					<span class="emoji" data-category="signs">⤵️</span>
					<span class="emoji" data-category="signs">🔀</span>
					<span class="emoji" data-category="signs">🔁</span>
					<span class="emoji" data-category="signs">🔂</span>
					<span class="emoji" data-category="signs">🔄</span>
					<span class="emoji" data-category="signs">🔃</span>
					<span class="emoji" data-category="signs">🎵</span>
					<span class="emoji" data-category="signs">🎶</span>
					<span class="emoji" data-category="signs">➕</span>
					<span class="emoji" data-category="signs">➖</span>
					<span class="emoji" data-category="signs">➗</span>
					<span class="emoji" data-category="signs">✖️</span>
					<span class="emoji" data-category="signs">🟰</span>
					<span class="emoji" data-category="signs">♾️</span>
					<span class="emoji" data-category="signs">💲</span>
					<span class="emoji" data-category="signs">💱</span>
					<span class="emoji" data-category="signs">™️</span>
					<span class="emoji" data-category="signs">©️</span>
					<span class="emoji" data-category="signs">®️</span>
					<span class="emoji" data-category="signs">👁️‍🗨️</span>
					<span class="emoji" data-category="signs">🔚</span>
					<span class="emoji" data-category="signs">🔙</span>
					<span class="emoji" data-category="signs">🔛</span>
					<span class="emoji" data-category="signs">🔝</span>
					<span class="emoji" data-category="signs">🔜</span>
					<span class="emoji" data-category="signs">〰️</span>
					<span class="emoji" data-category="signs">➰</span>
					<span class="emoji" data-category="signs">➿</span>
					<span class="emoji" data-category="signs">✔️</span>
					<span class="emoji" data-category="signs">☑️</span>
					<span class="emoji" data-category="signs">🔘</span>
					<span class="emoji" data-category="signs">🔴</span>
					<span class="emoji" data-category="signs">🟠</span>
					<span class="emoji" data-category="signs">🟡</span>
					<span class="emoji" data-category="signs">🟢</span>
					<span class="emoji" data-category="signs">🔵</span>
					<span class="emoji" data-category="signs">🟣</span>
					<span class="emoji" data-category="signs">⚫</span>
					<span class="emoji" data-category="signs">⚪</span>
					<span class="emoji" data-category="signs">🟤</span>
					<span class="emoji" data-category="signs">🔺</span>
					<span class="emoji" data-category="signs">🔻</span>
					<span class="emoji" data-category="signs">🔸</span>
					<span class="emoji" data-category="signs">🔹</span>
					<span class="emoji" data-category="signs">🔶</span>
					<span class="emoji" data-category="signs">🔷</span>
					<span class="emoji" data-category="signs">🔳</span>
					<span class="emoji" data-category="signs">🔲</span>
					<span class="emoji" data-category="signs">▪️</span>
					<span class="emoji" data-category="signs">▫️</span>
					<span class="emoji" data-category="signs">◾</span>
					<span class="emoji" data-category="signs">◽</span>
					<span class="emoji" data-category="signs">◼️</span>
					<span class="emoji" data-category="signs">◻️</span>
					<span class="emoji" data-category="signs">🟥</span>
					<span class="emoji" data-category="signs">🟧</span>
					<span class="emoji" data-category="signs">🟨</span>
					<span class="emoji" data-category="signs">🟩</span>
					<span class="emoji" data-category="signs">🟦</span>
					<span class="emoji" data-category="signs">🟪</span>
					<span class="emoji" data-category="signs">⬛</span>
					<span class="emoji" data-category="signs">⬜</span>
					<span class="emoji" data-category="signs">🟫</span>
					<span class="emoji" data-category="signs">🔈</span>
					<span class="emoji" data-category="signs">🔇</span>
					<span class="emoji" data-category="signs">🔉</span>
					<span class="emoji" data-category="signs">🔊</span>
					<span class="emoji" data-category="signs">🔔</span>
					<span class="emoji" data-category="signs">🔕</span>
					<span class="emoji" data-category="signs">📣</span>
					<span class="emoji" data-category="signs">📢</span>
					<span class="emoji" data-category="signs">💬</span>
					<span class="emoji" data-category="signs">💭</span>
					<span class="emoji" data-category="signs">🗯️</span>
					<span class="emoji" data-category="signs">♠️</span>
					<span class="emoji" data-category="signs">♣️</span>
					<span class="emoji" data-category="signs">♥️</span>
					<span class="emoji" data-category="signs">♦️</span>
					<span class="emoji" data-category="signs">🃏</span>
					<span class="emoji" data-category="signs">🎴</span>
					<span class="emoji" data-category="signs">🀄</span>
					<span class="emoji" data-category="signs">🕐</span>
					<span class="emoji" data-category="signs">🕑</span>
					<span class="emoji" data-category="signs">🕒</span>
					<span class="emoji" data-category="signs">🕓</span>
					<span class="emoji" data-category="signs">🕔</span>
					<span class="emoji" data-category="signs">🕕</span>
					<span class="emoji" data-category="signs">🕖</span>
					<span class="emoji" data-category="signs">🕗</span>
					<span class="emoji" data-category="signs">🕘</span>
					<span class="emoji" data-category="signs">🕙</span>
					<span class="emoji" data-category="signs">🕚</span>
					<span class="emoji" data-category="signs">🕛</span>
					<span class="emoji" data-category="signs">🕜</span>
					<span class="emoji" data-category="signs">🕝</span>
					<span class="emoji" data-category="signs">🕞</span>
					<span class="emoji" data-category="signs">🕟</span>
					<span class="emoji" data-category="signs">🕠</span>
					<span class="emoji" data-category="signs">🕡</span>
					<span class="emoji" data-category="signs">🕢</span>
					<span class="emoji" data-category="signs">🕣</span>
					<span class="emoji" data-category="signs">🕤</span>
					<span class="emoji" data-category="signs">🕥</span>
					<span class="emoji" data-category="signs">🕦</span>
					<span class="emoji" data-category="signs">🕧</span>



<!----------------------------------Signs End --------------------------------------------------------------------------------->



<!-----------------------------------Plants Start--------------------------------------------------------------------->
					
					<span class="emoji" data-category="plants">🌵</span>
					<span class="emoji" data-category="plants">🎄</span>
					<span class="emoji" data-category="plants">🌲</span>
					<span class="emoji" data-category="plants">🌳</span>
					<span class="emoji" data-category="plants">🌴</span>
					<span class="emoji" data-category="plants">🪵</span>
					<span class="emoji" data-category="plants">🌱</span>
					<span class="emoji" data-category="plants">🌿</span>
					<span class="emoji" data-category="plants">☘️</span>
					<span class="emoji" data-category="plants">🍀</span>
					<span class="emoji" data-category="plants">🎍</span>
					<span class="emoji" data-category="plants">🪴</span>
					<span class="emoji" data-category="plants">🎋</span>
					<span class="emoji" data-category="plants">🍃</span>
					<span class="emoji" data-category="plants">🍂</span>
					<span class="emoji" data-category="plants">🍁</span>
					<span class="emoji" data-category="plants">🍄</span>
					<span class="emoji" data-category="plants">🌾</span>
					<span class="emoji" data-category="plants">💐</span>
					<span class="emoji" data-category="plants">🌷</span>
					<span class="emoji" data-category="plants">🌹</span>
					<span class="emoji" data-category="plants">🥀</span>
					<span class="emoji" data-category="plants">🌺</span>
					<span class="emoji" data-category="plants">🌸</span>
					<span class="emoji" data-category="plants">🌼</span>
					<span class="emoji" data-category="plants">🌻</span>
<!----------------------------------------------plants End-------------------------------------------------------->


<!----------------------------------------------weather start----------------------------------------------------------->
					<span class="emoji" data-category="weather">🌞</span>
					<span class="emoji" data-category="weather">🌝</span>
					<span class="emoji" data-category="weather">🌛</span>
					<span class="emoji" data-category="weather">🌜</span>
					<span class="emoji" data-category="weather">🌚</span>
					<span class="emoji" data-category="weather">🌕</span>
					<span class="emoji" data-category="weather">🌖</span>
					<span class="emoji" data-category="weather">🌗</span>
					<span class="emoji" data-category="weather">🌘</span>
					<span class="emoji" data-category="weather">🌑</span>
					<span class="emoji" data-category="weather">🌒</span>
					<span class="emoji" data-category="weather">🌓</span>
					<span class="emoji" data-category="weather">🌔</span>
					<span class="emoji" data-category="weather">🌙</span>
					<span class="emoji" data-category="weather">🌎</span>
					<span class="emoji" data-category="weather">🌍</span>
					<span class="emoji" data-category="weather">🌏</span>
					<span class="emoji" data-category="weather">🪐</span>
					<span class="emoji" data-category="weather">💫</span>
					<span class="emoji" data-category="weather">⭐</span>
					<span class="emoji" data-category="weather">🌟</span>
					<span class="emoji" data-category="weather">✨</span>
					<span class="emoji" data-category="weather">⚡</span>
					<span class="emoji" data-category="weather">☄️</span>
					<span class="emoji" data-category="weather">💥</span>
					<span class="emoji" data-category="weather">🔥</span>
					<span class="emoji" data-category="weather">🌪️</span>
					<span class="emoji" data-category="weather">🌈</span>
					<span class="emoji" data-category="weather">☀️</span>
					<span class="emoji" data-category="weather">🌤️</span>
					<span class="emoji" data-category="weather">⛅</span>
					<span class="emoji" data-category="weather">🌥️</span>
					<span class="emoji" data-category="weather">☁️</span>
					<span class="emoji" data-category="weather">🌦️</span>
					<span class="emoji" data-category="weather">🌧️</span>
					<span class="emoji" data-category="weather">⛈️</span>
					<span class="emoji" data-category="weather">🌩️</span>
					<span class="emoji" data-category="weather">🌨️</span>
					<span class="emoji" data-category="weather">❄️</span>
					<span class="emoji" data-category="weather">☃️</span>
					<span class="emoji" data-category="weather">⛄</span>
					<span class="emoji" data-category="weather">🌬️</span>
					<span class="emoji" data-category="weather">💨</span>
					<span class="emoji" data-category="weather">💧</span>
					<span class="emoji" data-category="weather">💦</span>
					<span class="emoji" data-category="weather">🫧</span>
					<span class="emoji" data-category="weather">☔</span>
					<span class="emoji" data-category="weather">☂️</span>
					<span class="emoji" data-category="weather">🌊</span>
					<span class="emoji" data-category="weather">🌫️</span>
	
				
<!----------------------------weather end---------------------------------------------------------->
                    

                    <!-- Add more emojis here -->
                    <!-- For demonstration, you can add more emojis here to see the scrolling behavior -->
                
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const emojiButton = document.getElementById('emoji-button');
            const emojiToggleBox = document.getElementById('emoji-toggle-box');
            const emojiTextarea = document.getElementById('msg');
            const emojiTabs = document.querySelectorAll('.tab');

            let selectedCategory = 'all';

            // Toggle emoji box when the emoji button is clicked
            emojiButton.addEventListener('click', function() {
				if (emojiToggleBox.style.display === 'none' || emojiToggleBox.style.display === '') {
					emojiToggleBox.style.display = 'block';
                    emojiToggleBox.style.zIndex = '1';
				} else {
					emojiToggleBox.style.display = 'none';
                    emojiToggleBox.style.zIndex = '0';
				}
			});

            // Handle emoji selection
            emojiToggleBox.addEventListener('click', function(event) {
                if (event.target.classList.contains('emoji')) {
                    const selectedEmoji = event.target.textContent;
                    emojiTextarea.value += selectedEmoji;
                }
            });

            // Switch emoji category tabs
            emojiTabs.forEach((tab) => {
                tab.addEventListener('click', function() {
                    emojiTabs.forEach((t) => t.classList.remove('active'));
                    tab.classList.add('active');
                    selectedCategory = tab.getAttribute('data-category');
                    filterEmojisToggle(selectedCategory);
                });
            });

            // Filter emojis by category in the toggle box
            function filterEmojisToggle(category) {
                const emojis = emojiToggleBox.querySelectorAll('.emoji');

                emojis.forEach((emoji) => {
                    if (category === 'all' || emoji.getAttribute('data-category') === category) {
                        emoji.style.display = 'inline-block';
                    } else {
                        emoji.style.display = 'none';
                    }
                });
            }
			
			
			 document.addEventListener('click', function(event) {
        if (!emojiToggleBox.contains(event.target) && event.target !== emojiButton) {
            emojiToggleBox.style.display = 'none';
        }
    });
			
			
        });
		
		
		
    </script>